spring:
  profiles: default
  application:
    name: "DSA Bot"
  server:
    port: 22222
  datasource:
    url: jdbc:postgresql://localhost:5432/dsa_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update

rainbowlabs:
  dsabot:
    token: ""
